name: 'Serverless Env Action'
description: 'Configures the Serverless Env Action to be used in github workflows'
inputs:
  tool-version:
    description: 'Serverless Env Action Tool Version'
    required: true
    default: '2.0.0'
runs:
  using: 'node16'
  main: 'index.js'
